// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Snapdi.Repositories.Context;

#nullable disable

namespace Snapdi.Repositories.Migrations
{
    [DbContext(typeof(SnapdiDbV2Context))]
    partial class SnapdiDbV2ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlogKeyword", b =>
                {
                    b.Property<int>("BlogId")
                        .HasColumnType("int");

                    b.Property<int>("KeywordId")
                        .HasColumnType("int");

                    b.HasKey("BlogId", "KeywordId");

                    b.ToTable("BlogKeyword");
                });

            modelBuilder.Entity("KeywordsInBlog", b =>
                {
                    b.Property<int>("BlogId")
                        .HasColumnType("int")
                        .HasColumnName("BlogID");

                    b.Property<int>("KeywordId")
                        .HasColumnType("int")
                        .HasColumnName("KeywordID");

                    b.HasKey("BlogId", "KeywordId")
                        .HasName("PK__Keywords__574B8D0CE2A6215B");

                    b.HasIndex("KeywordId");

                    b.ToTable("KeywordsInBlog", (string)null);
                });

            modelBuilder.Entity("Snapdi.Repositories.Models.Blog", b =>
                {
                    b.Property<int>("BlogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BlogID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BlogId"));

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int")
                        .HasColumnName("AuthorID");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime");

                    b.HasKey("BlogId")
                        .HasName("PK__Blog__54379E506DDA2403");

                    b.HasIndex("AuthorId");

                    b.ToTable("Blog");
                });

            modelBuilder.Entity("Snapdi.Repositories.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BookingID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CustomerID");

                    b.Property<string>("LocationAddress")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LocationCity")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PhotographerId")
                        .HasColumnType("int")
                        .HasColumnName("PhotographerID");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<DateTime>("ScheduleAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("StatusID");

                    b.Property<int?>("StyleId")
                        .HasColumnType("int")
                        .HasColumnName("StyleID");

                    b.HasKey("BookingId")
                        .HasName("PK__Booking__73951ACDC273B8F2");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PhotographerId");

                    b.HasIndex("StatusId");

                    b.HasIndex("StyleId");

                    b.ToTable("Booking");
                });

            modelBuilder.Entity("Snapdi.Repositories.Models.BookingStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StatusID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StatusId")
                        .HasName("PK__BookingS__C8EE20438C9AFA58");

                    b.ToTable("BookingStatus");
                });

            modelBuilder.Entity("Snapdi.Repositories.Models.Conversation", b =>
                {
                    b.Property<int>("ConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ConversationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConversationId"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ConversationId")
                        .HasName("PK__Conversa__C050D897EF513182");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("Snapdi.Repositories.Models.ConversationParticipant", b =>
                {
                    b.Property<int>("ConversationId")
                        .HasColumnType("int")
                        .HasColumnName("ConversationID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("LastReadAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("LastReadMessageId")
                        .HasColumnType("int");

                    b.HasKey("ConversationId", "UserId")
                        .HasName("PK__Conversa__1128545DD045149E");

                    b.HasIndex("UserId");

                    b.ToTable("ConversationParticipants");
                });

            modelBuilder.Entity("Snapdi.Repositories.Models.FeePolicy", b =>
                {
                    b.Property<int>("FeePolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FeePolicyID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeePolicyId"));

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime");

                    b.Property<double>("FeePercent")
                        .HasColumnType("float");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("TransactionType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("FeePolicyId")
                        .HasName("PK__FeePolic__ADCA966AAC41B8C5");

                    b.ToTable("FeePolicy");
                });

            modelBuilder.Entity("Snapdi.Repositories.Models.Keyword", b =>
                {
                    b.Property<int>("KeywordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("KeywordID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KeywordId"));

                    b.Property<string>("Keyword1")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Keyword");

                    b.HasKey("KeywordId")
                        .HasName("PK__Keyword__37C135C1F834A132");

                    b.ToTable("Keyword");
                });

            modelBuilder.Entity("Snapdi.Repositories.Models.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MessageID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ConversationId")
                        .HasColumnType("int")
                        .HasColumnName("ConversationID");

                    b.Property<DateTime?>("ExpiredDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("SendAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("SenderId")
                        .HasColumnType("int")
                        .HasColumnName("SenderID");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MessageId")
                        .HasName("PK__Messages__C87C037C0DF786B5");

                    b.HasIndex("ConversationId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Snapdi.Repositories.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PaymentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int?>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("BookingID");

                    b.Property<double?>("FeeAmount")
                        .HasColumnType("float");

                    b.Property<double?>("FeePercent")
                        .HasColumnType("float");

                    b.Property<int?>("FeePolicyId")
                        .HasColumnType("int")
                        .HasColumnName("FeePolicyID");

                    b.Property<double?>("NetAmount")
                        .HasColumnType("float");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("PaymentStatusId")
                        .HasColumnType("int")
                        .HasColumnName("PaymentStatusID");

                    b.Property<string>("TransactionMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TransactionReference")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("PaymentId")
                        .HasName("PK__Payment__9B556A5840ED1111");

                    b.HasIndex("BookingId");

                    b.HasIndex("FeePolicyId");

                    b.HasIndex("PaymentStatusId");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("Snapdi.Repositories.Models.PaymentStatus", b =>
                {
                    b.Property<int>("PaymentStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PaymentStatusID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentStatusId"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PaymentStatusId")
                        .HasName("PK__PaymentS__34F8AC1F9AB83D1F");

                    b.ToTable("PaymentStatus");
                });

            modelBuilder.Entity("Snapdi.Repositories.Models.PhotoPortfolio", b =>
                {
                    b.Property<int>("PhotoPortfolioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PhotoPortfolioID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhotoPortfolioId"));

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("PhotoPortfolioId")
                        .HasName("PK__PhotoPor__75BE09A8AE74CC21");

                    b.HasIndex("UserId");

                    b.ToTable("PhotoPortfolio");
                });

            modelBuilder.Entity("Snapdi.Repositories.Models.PhotographerProfile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<double?>("AvgRating")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EquipmentDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("LevelPhotographer")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("YearsOfExperience")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId")
                        .HasName("PK__Photogra__1788CCACD97935F9");

                    b.ToTable("PhotographerProfile");
                });

            modelBuilder.Entity("Snapdi.Repositories.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReviewID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<int?>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("BookingID");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("FromUserId")
                        .HasColumnType("int")
                        .HasColumnName("FromUserID");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int?>("ToUserId")
                        .HasColumnType("int")
                        .HasColumnName("ToUserID");

                    b.HasKey("ReviewId")
                        .HasName("PK__Review__74BC79AE14FA1EB8");

                    b.HasIndex("BookingId");

                    b.HasIndex("FromUserId");

                    b.HasIndex("ToUserId");

                    b.ToTable("Review");
                });

            modelBuilder.Entity("Snapdi.Repositories.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RoleId")
                        .HasName("PK__Role__8AFACE3AD61AC071");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Snapdi.Repositories.Models.Style", b =>
                {
                    b.Property<int>("StyleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StyleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StyleId"));

                    b.Property<string>("StyleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StyleId")
                        .HasName("PK__Styles__8AD147A0C035264E");

                    b.ToTable("Styles");
                });

            modelBuilder.Entity("Snapdi.Repositories.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("ExpiredRefreshTokenAt")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerify")
                        .HasColumnType("bit");

                    b.Property<string>("LocationAddress")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LocationCity")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.HasKey("UserId")
                        .HasName("PK__User__1788CCAC98BF1C87");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "UQ__User__A9D10534DB5CBBA4")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("Snapdi.Repositories.Models.Voucher", b =>
                {
                    b.Property<int>("VoucherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VoucherID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VoucherId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DiscountType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("DiscountValue")
                        .HasColumnType("float");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<double?>("MaxDiscount")
                        .HasColumnType("float");

                    b.Property<double?>("MinSpend")
                        .HasColumnType("float");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("UsageLimit")
                        .HasColumnType("int");

                    b.HasKey("VoucherId")
                        .HasName("PK__Voucher__3AEE79C1B9C1175C");

                    b.HasIndex(new[] { "Code" }, "UQ__Voucher__A25C5AA7912D9D85")
                        .IsUnique();

                    b.ToTable("Voucher");
                });

            modelBuilder.Entity("Snapdi.Repositories.Models.VoucherUsage", b =>
                {
                    b.Property<int>("VoucherUsageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VoucherUsageID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VoucherUsageId"));

                    b.Property<int?>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("BookingID");

                    b.Property<DateTime>("UsedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<int?>("VoucherId")
                        .HasColumnType("int")
                        .HasColumnName("VoucherID");

                    b.HasKey("VoucherUsageId")
                        .HasName("PK__VoucherU__4264F82BBFB948C0");

                    b.HasIndex("BookingId");

                    b.HasIndex("UserId");

                    b.HasIndex("VoucherId");

                    b.ToTable("VoucherUsage");
                });

            modelBuilder.Entity("KeywordsInBlog", b =>
                {
                    b.HasOne("Snapdi.Repositories.Models.Blog", null)
                        .WithMany()
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__KeywordsI__BlogI__4222D4EF");

                    b.HasOne("Snapdi.Repositories.Models.Keyword", null)
                        .WithMany()
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__KeywordsI__Keywo__4316F928");
                });

            modelBuilder.Entity("Snapdi.Repositories.Models.Blog", b =>
                {
                    b.HasOne("Snapdi.Repositories.Models.User", "Author")
                        .WithMany("Blogs")
                        .HasForeignKey("AuthorId")
                        .HasConstraintName("FK__Blog__AuthorID__3F466844");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Snapdi.Repositories.Models.Booking", b =>
                {
                    b.HasOne("Snapdi.Repositories.Models.User", "Customer")
                        .WithMany("BookingCustomers")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("FK__Booking__Custome__534D60F1");

                    b.HasOne("Snapdi.Repositories.Models.User", "Photographer")
                        .WithMany("BookingPhotographers")
                        .HasForeignKey("PhotographerId")
                        .HasConstraintName("FK__Booking__Photogr__5441852A");

                    b.HasOne("Snapdi.Repositories.Models.BookingStatus", "Status")
                        .WithMany("Bookings")
                        .HasForeignKey("StatusId")
                        .HasConstraintName("FK__Booking__StatusI__5629CD9C");

                    b.HasOne("Snapdi.Repositories.Models.Style", "Style")
                        .WithMany("Bookings")
                        .HasForeignKey("StyleId")
                        .HasConstraintName("FK__Booking__StyleID__5535A963");

                    b.Navigation("Customer");

                    b.Navigation("Photographer");

                    b.Navigation("Status");

                    b.Navigation("Style");
                });

            modelBuilder.Entity("Snapdi.Repositories.Models.ConversationParticipant", b =>
                {
                    b.HasOne("Snapdi.Repositories.Models.Conversation", "Conversation")
                        .WithMany("ConversationParticipants")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Conversat__Conve__6FE99F9F");

                    b.HasOne("Snapdi.Repositories.Models.User", "User")
                        .WithMany("ConversationParticipants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Conversat__UserI__70DDC3D8");

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Snapdi.Repositories.Models.Message", b =>
                {
                    b.HasOne("Snapdi.Repositories.Models.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Messages__Conver__73BA3083");

                    b.HasOne("Snapdi.Repositories.Models.User", "Sender")
                        .WithMany("Messages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Messages__Sender__74AE54BC");

                    b.Navigation("Conversation");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Snapdi.Repositories.Models.Payment", b =>
                {
                    b.HasOne("Snapdi.Repositories.Models.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Payment__Booking__693CA210");

                    b.HasOne("Snapdi.Repositories.Models.FeePolicy", "FeePolicy")
                        .WithMany("Payments")
                        .HasForeignKey("FeePolicyId")
                        .HasConstraintName("FK__Payment__FeePoli__6A30C649");

                    b.HasOne("Snapdi.Repositories.Models.PaymentStatus", "PaymentStatus")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentStatusId")
                        .HasConstraintName("FK__Payment__Payment__6B24EA82");

                    b.Navigation("Booking");

                    b.Navigation("FeePolicy");

                    b.Navigation("PaymentStatus");
                });

            modelBuilder.Entity("Snapdi.Repositories.Models.PhotoPortfolio", b =>
                {
                    b.HasOne("Snapdi.Repositories.Models.User", "User")
                        .WithMany("PhotoPortfolios")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__PhotoPort__UserI__PhotoPortfolio_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Snapdi.Repositories.Models.PhotographerProfile", b =>
                {
                    b.HasOne("Snapdi.Repositories.Models.User", "User")
                        .WithOne("PhotographerProfile")
                        .HasForeignKey("Snapdi.Repositories.Models.PhotographerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Photograp__UserI__4AB81AF0");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Snapdi.Repositories.Models.Review", b =>
                {
                    b.HasOne("Snapdi.Repositories.Models.Booking", "Booking")
                        .WithMany("Reviews")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Review__BookingI__59063A47");

                    b.HasOne("Snapdi.Repositories.Models.User", "FromUser")
                        .WithMany("ReviewFromUsers")
                        .HasForeignKey("FromUserId")
                        .HasConstraintName("FK__Review__FromUser__59FA5E80");

                    b.HasOne("Snapdi.Repositories.Models.User", "ToUser")
                        .WithMany("ReviewToUsers")
                        .HasForeignKey("ToUserId")
                        .HasConstraintName("FK__Review__ToUserID__5AEE82B9");

                    b.Navigation("Booking");

                    b.Navigation("FromUser");

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("Snapdi.Repositories.Models.User", b =>
                {
                    b.HasOne("Snapdi.Repositories.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK__User__RoleID__3C69FB99");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Snapdi.Repositories.Models.VoucherUsage", b =>
                {
                    b.HasOne("Snapdi.Repositories.Models.Booking", "Booking")
                        .WithMany("VoucherUsages")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__VoucherUs__Booki__60A75C0F");

                    b.HasOne("Snapdi.Repositories.Models.User", "User")
                        .WithMany("VoucherUsages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__VoucherUs__UserI__628FA481");

                    b.HasOne("Snapdi.Repositories.Models.Voucher", "Voucher")
                        .WithMany("VoucherUsages")
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__VoucherUs__Vouch__619B8048");

                    b.Navigation("Booking");

                    b.Navigation("User");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("Snapdi.Repositories.Models.Booking", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Reviews");

                    b.Navigation("VoucherUsages");
                });

            modelBuilder.Entity("Snapdi.Repositories.Models.BookingStatus", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("Snapdi.Repositories.Models.Conversation", b =>
                {
                    b.Navigation("ConversationParticipants");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Snapdi.Repositories.Models.FeePolicy", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Snapdi.Repositories.Models.PaymentStatus", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Snapdi.Repositories.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Snapdi.Repositories.Models.Style", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("Snapdi.Repositories.Models.User", b =>
                {
                    b.Navigation("Blogs");

                    b.Navigation("BookingCustomers");

                    b.Navigation("BookingPhotographers");

                    b.Navigation("ConversationParticipants");

                    b.Navigation("Messages");

                    b.Navigation("PhotoPortfolios");

                    b.Navigation("PhotographerProfile");

                    b.Navigation("ReviewFromUsers");

                    b.Navigation("ReviewToUsers");

                    b.Navigation("VoucherUsages");
                });

            modelBuilder.Entity("Snapdi.Repositories.Models.Voucher", b =>
                {
                    b.Navigation("VoucherUsages");
                });
#pragma warning restore 612, 618
        }
    }
}
