// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Snapdi.Repositories.Models;

public partial class Blog
{
    public int BlogId { get; set; }

    public int? KeywordId { get; set; }

    public int? AuthorId { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public DateTime CreateAt { get; set; }

    public DateTime? UpdateAt { get; set; }

    public bool IsActive { get; set; }

    public virtual User Author { get; set; }

    public virtual Keyword Keyword { get; set; }
}