// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Snapdi.Repositories.Models;

public partial class Booking
{
    public int BookingId { get; set; }

    public int? CustomerId { get; set; }

    public int? PhotographerId { get; set; }

    public DateTime ScheduleAt { get; set; }

    public string LocationCity { get; set; }

    public string LocationAddress { get; set; }

    public int? StyleId { get; set; }

    public int? StatusId { get; set; }

    public double Price { get; set; }

    public virtual User Customer { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual User Photographer { get; set; }

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    public virtual BookingStatus Status { get; set; }

    public virtual Style Style { get; set; }

    public virtual ICollection<VoucherUsage> VoucherUsages { get; set; } = new List<VoucherUsage>();
}