// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Snapdi.Repositories.Models;

public partial class Keyword
{
    public int KeywordId { get; set; }

    public string Keyword1 { get; set; }

    public virtual ICollection<Blog> Blogs { get; set; } = new List<Blog>();
}