// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Snapdi.Repositories.Models;

public partial class Payment
{
    public int PaymentId { get; set; }

    public int? BookingId { get; set; }

    public double Amount { get; set; }

    public int? FeePolicyId { get; set; }

    public double? FeePercent { get; set; }

    public double? FeeAmount { get; set; }

    public double? NetAmount { get; set; }

    public string TransactionMethod { get; set; }

    public string TransactionReference { get; set; }

    public int? PaymentStatusId { get; set; }

    public DateTime PaymentDate { get; set; }

    public virtual Booking Booking { get; set; }

    public virtual FeePolicy FeePolicy { get; set; }

    public virtual PaymentStatus PaymentStatus { get; set; }
}