// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Snapdi.Repositories.Models;

public partial class PhotoEquipment
{
    public int EquipmentId { get; set; }

    public int? UserId { get; set; }

    public string Name { get; set; }

    public virtual ICollection<PhotographerProfile> PhotographerProfiles { get; set; } = new List<PhotographerProfile>();

    public virtual User User { get; set; }
}