// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Snapdi.Repositories.Models;

public partial class PhotographerProfile
{
    public int UserId { get; set; }

    public int? EquipmentId { get; set; }

    public double? AvgRating { get; set; }

    public bool IsAvailable { get; set; }

    public string Description { get; set; }

    public int? PhotoPortfolioId { get; set; }

    public virtual PhotoEquipment Equipment { get; set; }

    public virtual PhotoPortfolio PhotoPortfolio { get; set; }

    public virtual User User { get; set; }
}