// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Snapdi.Repositories.Models;

public partial class PhotoPortfolio
{
    public int PhotoPortfolioId { get; set; }

    public string PhotoUrl { get; set; }

    public virtual ICollection<PhotographerProfile> PhotographerProfiles { get; set; } = new List<PhotographerProfile>();
}