// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Snapdi.Repositories.Models;

public partial class Review
{
    public int ReviewId { get; set; }

    public int? BookingId { get; set; }

    public int? FromUserId { get; set; }

    public int? ToUserId { get; set; }

    public double Rating { get; set; }

    public string Comment { get; set; }

    public DateTime CreateAt { get; set; }

    public virtual Booking Booking { get; set; }

    public virtual User FromUser { get; set; }

    public virtual User ToUser { get; set; }
}