// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Snapdi.Repositories.Models;

public partial class Style
{
    public int StyleId { get; set; }

    public string StyleName { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();
}