// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Snapdi.Repositories.Models;

public partial class User
{
    public int UserId { get; set; }

    public int? RoleId { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string Password { get; set; }

    public string RefreshToken { get; set; }

    public DateTime? ExpiredRefreshTokenAt { get; set; }

    public bool IsActive { get; set; }

    public bool IsVerify { get; set; }

    public DateTime CreatedAt { get; set; }

    public string LocationAddress { get; set; }

    public string LocationCity { get; set; }

    public string AvatarUrl { get; set; }

    public virtual ICollection<Blog> Blogs { get; set; } = new List<Blog>();

    public virtual ICollection<Booking> BookingCustomers { get; set; } = new List<Booking>();

    public virtual ICollection<Booking> BookingPhotographers { get; set; } = new List<Booking>();

    public virtual ICollection<ConversationParticipant> ConversationParticipants { get; set; } = new List<ConversationParticipant>();

    public virtual ICollection<Message> Messages { get; set; } = new List<Message>();

    public virtual ICollection<PhotoEquipment> PhotoEquipments { get; set; } = new List<PhotoEquipment>();

    public virtual PhotographerProfile PhotographerProfile { get; set; }

    public virtual ICollection<Review> ReviewFromUsers { get; set; } = new List<Review>();

    public virtual ICollection<Review> ReviewToUsers { get; set; } = new List<Review>();

    public virtual Role Role { get; set; }

    public virtual ICollection<VoucherUsage> VoucherUsages { get; set; } = new List<VoucherUsage>();
}