// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Snapdi.Repositories.Models;

public partial class Voucher
{
    public int VoucherId { get; set; }

    public string Code { get; set; }

    public string Description { get; set; }

    public string DiscountType { get; set; }

    public double DiscountValue { get; set; }

    public double? MaxDiscount { get; set; }

    public double? MinSpend { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public int? UsageLimit { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<VoucherUsage> VoucherUsages { get; set; } = new List<VoucherUsage>();
}