// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Snapdi.Repositories.Models;

public partial class VoucherUsage
{
    public int VoucherUsageId { get; set; }

    public int? BookingId { get; set; }

    public int? VoucherId { get; set; }

    public int? UserId { get; set; }

    public DateTime UsedAt { get; set; }

    public virtual Booking Booking { get; set; }

    public virtual User User { get; set; }

    public virtual Voucher Voucher { get; set; }
}